// user-frontend/src/app/user/pages/login/login.component.ts
import { Component } from '@angular/core';
import { FormControl, FormGroup, Validators } from '@angular/forms';

@Component({
  selector: 'app-login',
  templateUrl: './login.component.html',
  styleUrl: './login.component.css'
})
export class LoginComponent {
  loginForm = new FormGroup({
    email: new FormControl('', [Validators.required]),
    password: new FormControl('', [Validators.required])
  })

  onSubmit() {
        
  }
}

<div class="flex justify-between items-center bg-white md:bg-[#f6f6f6] h-[89vh]">
    <div class="hidden lg:block">
        <!-- text here -->
    </div>

    <div class="w-[100vw] md:w-auto mx-auto lg:mx-0 mt-5">
        <div class="flex flex-col text-center bg-white shadow-sm lg:mr-28">
            <h2 class="font-semibold text-[#61594f] text-base md:text-lg mt-5 md:mt-12">
                REGISTERED CUSTOMERS
            </h2>
            <p class="text-[#b7adb1] text-xs md:text-sm font-[500] px-5 pt-9 mb-5">
                If you have an account with us, Please login!
            </p>
            <form class="px-7" [formGroup]="loginForm">
                <div class="mb-5">
                    <input
                        class="placeholder:text-[#b7adb1] focus:outline-none focus:ring-0 md:text-sm text-xs font-[500] bg-[#f6f6f6] border-none w-[16rem] md:w-[30rem] h-11"
                        type="email" placeholder="Email here..." formControlName="email" />
                </div>

                <div class="mb-5">
                    <input
                        class="placeholder:text-[#b7adb1] focus:outline-none focus:ring-0 md:text-sm text-xs font-[500] bg-[#f6f6f6] border-none w-[16rem] md:w-[30rem] h-11"
                        type="password" placeholder="Password" formControlName="password" />
                </div>
            </form>
            <div class="mb-12">
                <p class="text-[#d7ac6f] mb-8 hover:text-[#eea43c] cursor-pointer">
                    Forget your password?
                </p>
                <button class="bg-[#c87065] text-sm md:text-base text-white w-32 h-10 md:h-12 hover:bg-[#e17061] transition" [disabled]="!loginForm.valid" (click)="onSubmit()">
                    LOGIN
                </button>
            </div>
        </div>
    </div>
</div>

// user-react/src/Login/Login.jsx
import logo from '../../../admin-frontend/src/assets/images/logo.png';

export default function Login() {
    return (
      <>
        <div className="flex min-h-full flex-1 flex-col justify-center px-6 py-12 lg:px-8">
          <div className="sm:mx-auto sm:w-full sm:max-w-sm">
            <img
              alt="Your Company"
              src={logo}
              className="mx-auto h-10 w-auto"
            />
            <h2 className="mt-10 text-center text-2xl font-bold leading-9 tracking-tight text-gray-900">
              Sign in to your account
            </h2>
          </div>
  
          <div className="mt-10 sm:mx-auto sm:w-full sm:max-w-sm">
            <form action="#" method="POST" className="space-y-6">
              <div>
                <label htmlFor="email" className="block text-sm font-medium leading-6 text-gray-900">
                  Email address
                </label>
                <div className="mt-2">
                  <input
                    id="email"
                    name="email"
                    type="email"
                    required
                    autoComplete="email"
                    className="block w-full rounded-md border-0 py-1.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:text-sm sm:leading-6"
                  />
                </div>
              </div>
  
              <div>
                <div className="flex items-center justify-between">
                  <label htmlFor="password" className="block text-sm font-medium leading-6 text-gray-900">
                    Password
                  </label>
                  <div className="text-sm">
                    <a href="#" className="font-semibold text-indigo-600 hover:text-indigo-500">
                      Forgot password?
                    </a>
                  </div>
                </div>
                <div className="mt-2">
                  <input
                    id="password"
                    name="password"
                    type="password"
                    required
                    autoComplete="current-password"
                    className="block w-full rounded-md border-0 py-1.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:text-sm sm:leading-6"
                  />
                </div>
              </div>
  
              <div>
                <button
                  type="submit"
                  className="flex w-full justify-center rounded-md bg-indigo-600 px-3 py-1.5 text-sm font-semibold leading-6 text-white shadow-sm hover:bg-indigo-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600"
                >
                  Sign in
                </button>
              </div>
            </form>
  
            <p className="mt-10 text-center text-sm text-gray-500">
              Not a member?{' '}
              <a href="#" className="font-semibold leading-6 text-indigo-600 hover:text-indigo-500">
                Register Here
              </a>
            </p>
          </div>
        </div>
      </>
    )
  }
